version: 2
jobs:
  build:
    docker:
      - image: haskell:8
    steps:
      - checkout
      - run:
          command: |
            FOO=5
            echo $FOO
      - run:
          command: |
            which stack || true
            which /usr/bin/stack || true
            which /usr/local/bin/stack || true
            echo $FOO || true
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
